ExamPrak7/Models/Appuser.cs
using Microsoft.AspNetCore.Identity;

namespace ExamPrak7.Models
{
    public class Appuser:IdentityUser
    {
        public string FisrtName { get; set; }
        public string LastName { get; set; }
    }
}

ExamPrak7/Models/Team.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamPrak7.Models
{
    public class Team
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string ImageUrl { get; set; }
        [NotMapped]
        public IFormFile Image { get; set; }
    }

}

ExamPrak7/Areas/Admin/Controllers/AuthController.cs
using ExamPrak7.Areas.Admin.ViewModel.Autho;
using ExamPrak7.Models;
using ExamPrak7.ViewModel.Autho;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ExamPrak7.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AuthController : Controller
    {
        public readonly UserManager<Appuser> _usermanager;
        public readonly SignInManager<Appuser> _signInManager;
        public AuthController(UserManager<Appuser> usermanager,SignInManager<Appuser> signInManager)
        {
            _usermanager = usermanager;
            _signInManager = signInManager; 
        }

        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async  Task<IActionResult> Register(RegisterVM register)
        {
            if (!ModelState.IsValid) return View();

            Appuser newUser = new Appuser()
            {
                FisrtName = register.FirstName,
                LastName = register.LastName,
                Email = register.Email,
                 UserName = register.UserName
            };
            IdentityResult result = await _usermanager.CreateAsync(newUser,register.Password);
            if (!result.Succeeded)
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                    return View();
                }
            }
            return RedirectToAction("Index");
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginVM Login,string returnUrl)
        {
            Appuser user;
            if (Login.UserNameOrEmail.Contains("@"))
                user = await _usermanager.FindByEmailAsync(Login.UserNameOrEmail);
            else
                user = await _usermanager.FindByNameAsync(Login.UserNameOrEmail);
            if (user == null)
            {
                ModelState.AddModelError("", "Login and user Wrong");
                return View(Login);
            }
            var result = await _signInManager.PasswordSignInAsync(user, Login.Password, Login.RememberMe, true);
            if (result.Succeeded)
            {
                ModelState.AddModelError("", "Nese YAnlisdir ");  
            }
            if (returnUrl != null) return LocalRedirect(returnUrl);

            return RedirectToAction("Index", "Dashboard");
        }
        public async Task<IActionResult> SignOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction(nameof(Register));
        }

    }
}

ExamPrak7/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ExamPrak7.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ExamPrak7/Areas/Admin/Controllers/TeamController.cs
using ExamPrak7.DAL;
using ExamPrak7.Models;
using ExamPrak7.Utilize;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace ExamPrak7.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]

    public class TeamController : Controller
    {
        public readonly AppDbContext _context;
        public readonly IWebHostEnvironment _env;
        public TeamController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public ActionResult Index()
        {
            List<Team> teams = _context.Teams.ToList();
            return View(teams);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Team team)
        {
            if (!ModelState.IsValid) return View();
            if (team.Image.CheckType("Image/"))
            {
                ModelState.AddModelError("Type", "Wrong Type");
                return View();
            }
            if (team.Image.CheckSize(1000))
            {
                ModelState.AddModelError("Size", "Wrong Size");
                return View();
            }
            if (team.Image != null)
            {
                team.ImageUrl = team.Image.SaveImg(Path.Combine(_env.WebRootPath, "images"));

            }
            _context.Teams.Add(team);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Edit(int id)
        {
            Team team = _context.Teams.Find(id);
            if (team == null)
            {
                return BadRequest();
            }
            return View(team);
        }

        // POST: TeamController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Team team)
        {
            if (id != team.Id)
            {
                return View();
            }
            Team DbTeam = _context.Teams.Find(id);
            if (team.Image.CheckType("images/"))
            {
                ModelState.AddModelError("Type", "Wrong Type");
                return View();
            }
            if (team.Image.CheckSize(1000))
            {
                ModelState.AddModelError("Size", "Wrong Size");
                return View();
            }
            if (team.Image != null)
            {
               
                Filemanager.DeleteFile(Path.Combine(_env.WebRootPath,"images" ,DbTeam.ImageUrl));
                DbTeam.ImageUrl = team.Image.SaveImg(Path.Combine(_env.WebRootPath, "images"));

            }
            DbTeam.Name = team.Name;
            DbTeam.Title = team.Title;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Delete(int id)
        {
            Team team = _context.Teams.Find(id);
            if (team == null)
            {
                return View();
            }
            Filemanager.DeleteFile(Path.Combine(_env.WebRootPath, team.ImageUrl));
            _context.Teams.Remove(team);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

    }
}

ExamPrak7/Controllers/HomeController.cs
using ExamPrak7.DAL;
using ExamPrak7.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace ExamPrak7.Controllers
{
    public class HomeController : Controller
    {
        public readonly AppDbContext _context;
        public HomeController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Team> teams = _context.Teams.ToList();
            return View(teams);
        }
    }
}

ExamPrak7/Areas/Admin/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

 <!-- MAIN CONTENT START -->
        <main>
             <!-- Page Content  -->
         <div class="content-wrapper">
            <div class="main-content">
               <nav class="navbar-custom-menu navbar navbar-expand-lg m-0">
                  <div class="sidebar-toggle-icon" id="sidebarCollapse">
                     sidebar toggle<span></span>
                  </div>
                  <!--/.sidebar toggle icon-->
                  <div class="d-flex flex-grow-1">
                     <ul class="navbar-nav flex-row align-items-center ml-auto">
                       
                        
                        <!--/.dropdown-->
                     </ul>
                     <!--/.navbar nav-->
                     <div class="nav-clock">
                        <div class="time">
                           <span class="time-hours"></span>
                           <span class="time-min"></span>
                           <span class="time-sec"></span>
                        </div>
                     </div>
                     <!-- nav-clock -->
                  </div>
               </nav>
             
            </div>
            <div class="overlay"></div>
         </div>
         <!--/.wrapper-->
        </main>

ExamPrak7/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Responsive Bootstrap 4 Admin &amp; Dashboard Template">
    <meta name="author" content="Bdtask">
    <title>Bhulua - Bootstrap 4 Admin Template Deshboard</title>
    <!-- App favicon -->
    <link rel="shortcut icon" href="~/admin/dist/img/favicon.png">
    <!--Global Styles(used by all pages)-->
    <link href="~/admin/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/admin/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">
    <link href="~/admin/plugins/fontawesome/css/all.min.css" rel="stylesheet">
    <link href="~/admin/plugins/typicons/src/typicons.min.css" rel="stylesheet">
    <link href="~/admin/plugins/themify-icons/themify-icons.min.css" rel="stylesheet">
    <!--Third party Styles(used by this page)--> 
    <link href="~/admin/plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
    <!--Start Your Custom Style Now-->
    <link href="~/admin/dist/css/style.css" rel="stylesheet">
</head>
<body class="fixed">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="preloader">
                <div class="spinner-layer pl-green">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>Please wait...</p>
        </div>
    </div>
    <!-- #END# Page Loader -->
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav class="sidebar sidebar-bunker">
            <div class="sidebar-header">
                <a re-controller="Dashboard" asp-action="Index" class="logo"><img src="~/admin/dist/img/logo.png" alt=""></a>
            </div>
            <!--/.sidebar header-->
            <div class="profile-element d-flex align-items-center flex-shrink-0">
                <div class="avatar online">
                    <img src="~/admin/dist/img/avatar-1.jpg" class="img-fluid rounded-circle" alt="">
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                <div class="profile-text">
                    <h6 class="m-0">@User.Identity.Name
                    </h6>
                </div>
                   <a class="btn btn-primary" asp-controller="Auth" asp-action="SignOut">Log Out</a>
                    
                }
            </div>
            <!--/.profile element-->
            <form class="search sidebar-form" action="#" method="get">
                <div class="search__inner">
                    <input type="text" class="search__text" placeholder="Search...">
                    <i class="typcn typcn-zoom-outline search__helper" data-sa-action="search-close"></i>
                </div>
            </form>
            <!--/.search-->
            <div class="sidebar-body">
                <nav class="sidebar-nav">
                    <ul class="metismenu">
                        <li class="nav-label">Main Menu</li>
                        <li>
                            <a class="has-arrow material-ripple" href="#">
                                <i class="typcn typcn-home-outline mr-2"></i>
                                Dashboard
                            </a>
                            <ul class="nav-second-level">
                                <li><a asp-controller="Team" asp-action="Index">Team CRUD</a></li>
                                <li><a asp-controller="Auth" asp-action="Register">Dashboard Two</a></li>
                            </ul>
                        </li>

                    </ul>
                </nav>
            </div>
            <!-- sidebar-body -->

        </nav>
   
         <div class="container">
             @RenderBody()
         </div>
            
 <!-- MAIN CONTENT END -->
        <footer class="footer-content">
            <div class="footer-text d-flex align-items-center justify-content-between">
            </div>
        </footer>
        <!--/.footer content-->
        <div class="overlay"></div>
    </div>
    <!--/.wrapper-->
    </div>
    <!--Global script(used by all pages)-->
    <script data-cfasync="false" src="cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script src="~/admin/plugins/jQuery/jquery-3.4.1.min.js"></script>
    <script src="~/admin/dist/js/popper.min.js"></script>
    <script src="~/admin/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/admin/plugins/metisMenu/metisMenu.min.js"></script>
    <script src="~/admin/plugins/perfect-scrollbar/dist/perfect-scrollbar.min.js"></script>
    <!-- Third Party Scripts(used by this page)-->
    <script src="~/admin/plugins/chartJs/Chart.min.js"></script>
    <script src="~/admin/plugins/sparkline/sparkline.min.js"></script>
    <script src="~/admin/plugins/datatables/dataTables.min.js"></script>
    <script src="~/admin/plugins/datatables/dataTables.bootstrap4.min.js"></script>
    <!--Page Active Scripts(used by this page)-->
    <script src="~/admin/dist/js/pages/dashboard.js"></script>
    <!--Page Scripts(used by all page)-->
    <script src="~/admin/dist/js/sidebar.js"></script>
</body>
<!-- Mirrored from bhulua.thememinister.com/blank-page.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 12 Oct 2019 13:14:22 GMT -->
</html>

ExamPrak7/Areas/Admin/Views/Team/Create.cshtml
@model Team
@{
    ViewData["Title"] = "Create";
}
<div class="card-body">
    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <input type="text" class="form-control" asp-for="@Model.Name"  placeholder="Enter Name">
        </div>
        <div class="form-group">
            <input type="text" class="form-control" asp-for="@Model.Title"  placeholder="Enter Title">
        </div>
        <div class="form-group">
            <input type="file" class="form-control" asp-for="@Model.Image">
        </div>
     
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
    
</div>

ExamPrak7/Areas/Admin/Views/Team/Edit.cshtml
@model Team
@{
    ViewData["Title"] = "Edit";
}
<div class="card-body">
    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <input type="text" class="form-control" asp-for="@Model.Name"  placeholder="Enter Name">
        </div>
        <div class="form-group">
            <input type="text" class="form-control" asp-for="@Model.Title"  placeholder="Enter Title">
        </div>
        <div class="form-group">
            <input type="file" class="form-control" asp-for="@Model.Image">
        </div>
     
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
    
</div>

ExamPrak7/Areas/Admin/Views/Team/Index.cshtml
@model List<Team>
@{
    ViewData["Title"] = "Index";
}
<div class="card-body">
    <div class="table-responsive">
        <table class="table">
            <thead>
                <a class="btn btn-primary-soft mb-1" asp-controller="Team" asp-action="Create">Add</a>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Title</th>
                    <th>Image</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
               {
                <tr>
                    <th scope="row">@item.Id</th>
                    <td>@item.Name</td>
                    <td>@item.Title</td>
                    <td><img style="width:100px;" src="~/images/@item.ImageUrl"></td>
                    <td><a class="btn btn-primary-soft mr-1" asp-controller="Team" asp-action="Edit" asp-route-id="@item.Id">Edit</a></td>
                    <td><a class="btn btn-danger-soft mr-1" asp-controller="Team" asp-action="Delete" asp-route-id="@item.Id">Delete</a></td>

                </tr>
               }
            </tbody>
        </table>
    </div>
</div>

ExamPrak7/Views/Home/Index.cshtml
@model List<Team>
@{
    ViewData["Title"] = "Index";
}
<section id="Create">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="aba">
                    <h1>Let us create...</h1>
                    <p>
                        You may contribute a small amount via PayPal if Nomad Force Template is useful for you.
                        This will absolutely help us to keep creating better CSS templates for you.

                        We provide you 100% free templates on TemplateMo website. Images are provided by FreePik
                        and Unsplash websites.
                    </p>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="aba">
                    <p class="right">
                        This Bootstrap 5 layout is free to use for your business. You are allowed
                        to edit it in any way you like. However, please do not redistribute this template ZIP
                        file for a template download purpose on any other website such as Free CSS collections.

                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="team">
    <div class="container1">
        <div class="row">
            <div class="col-lg-5">
                <div class="row">
                    <div class="col-lg-7">
                        <div class="images">
                            <img src="./assets/img/team1.png" alt="">
                        </div>
                    </div>
                    <div class="col-lg-5">
                        <div class="about">
                            <h1>We’re - idealists and strategic thinkers.</h1>
                            <p>Over six years in the video business</p>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-7">
                <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-indicators">
                        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
                    </div>
                    <div class="carousel-inner">
                        @for (var i = 0; i < @Model.Count; i++)
                        {
                            if (i == 0)
                            {
                                <div class="carousel-item active">
                                    <img style="width:80%;" src="~/images/@Model[i].ImageUrl" class="d-block " alt="...">
                                    <div class="carousel-caption d-none d-md-block">
                                       <h5>@Model[i].Name</h5>
                                    <p>@Model[i].Title</p>
                                    </div>
                                </div>
                            }
                            else
                            {
                               <div class="carousel-item">
                                <img style="width:80%;" src="~/images/@Model[i].ImageUrl" class="d-block " alt="...">
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>@Model[i].Name</h5>
                                    <p>@Model[i].Title</p>
                                </div>
                            </div>
                            }
                            
                        }

                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </div>

</section>
    <section id="Portfolio">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="images">
                            <img src="./assets/img/port1.jpeg" alt="">
                            <h1>Effortless</h1>
                            <p>Branding</p>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="images">
                            <img src="./assets/img/port2.jpeg" alt="">
                            <h1>Maki
                            </h1>
                            <p>Website</p>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="images">
                            <img src="./assets/img/part3.jpeg" alt="">
                            <h1>Health technology</h1>
                            <p>Art Direction</p>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="images">
                            <img src="./assets/img/part4.jpeg" alt="">
                            <h1>The gig economy</h1>
                            <p>Graphic</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section id="News">
            <div class="container">
                <div class="row">
                    <div style="text-align: center;" class="new">
                        <h1>News & Events
                        </h1>
                    </div>
                    <div class="col-lg-6">
                        <div class="images">
                            <img src="./assets/img/news1.jpg" alt="">
                            <a class="btn " href="#">The rise of the gig economy spells the end for these workers the old system</a>
                            <p>22 hours Ago</p>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="content">
                                    <img style="width: 50%;" src="./assets/img/right.jpeg" alt="">
                                    <div class="ab">
                                        <h4>Job Opportunities: Digital, Marketing</h4>
                                        <p>Alaska,
                                            August 6, 2021</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="content">
                                    <img style="width: 50%;" src="./assets/img/right.jpeg" alt="">
                                    <div class="ab">
                                        <h4>Job Opportunities: Digital, Marketing</h4>
                                        <p>Alaska,
                                            August 6, 2021</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section id="Form">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 style=>Dont' be shy, write to us</h1>
                        <form>
                            <div class="mb-3 ">
                              <label for="exampleInputEmail1" class="form-label">Name *</label>
                              <input style="width:20% ;" type="text" class="form-control">
                            </div>
                            <div class="mb-3 ">
                                <label for="exampleInputEmail1" class="form-label">E-mail *</label>
                                <input style="width:20% !important ;" type="email" class="form-control w-10" id="exampleInputEmail1" aria-describedby="emailHelp">
                              </div>
                              <div class="mb-3 ">
                                  <textarea name="" id="" cols="20" rows="10" class="form-label"></textarea>
                              </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                          </form>
                    </div>
                </div>
            </div>
        </section>
        <section id="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d24314.776993010873!2d49.786691665649414!3d40.37899861642784!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40307df206d8c7a7%3A0x5c02d6a3a17a28ea!2sBaku%20%E2%80%9CASAN%20service%E2%80%9D%20center%20No.3!5e0!3m2!1sen!2s!4v1656315947037!5m2!1sen!2s" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </section>